# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
cache: pip
python:
    - "3.7"
    - "3.6"

install:
    - pip install -U tox-travis codecov

script:
    - tox

after_success:
    - ls
    - coverage report
    - mv .coverage .coverage.travis
    - appveyor-artifacts -m download
    - coverage combine
    - coverage report
    - coveralls
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)
