# Config file for automatic testing at travis-ci.org

language: python

python:
    - "3.6"
#    - "3.7"

sudo: false

os:
    # Python builds are not available on the OSX environment.
    # see: https://docs.travis-ci.com/user/languages/python
    #- osx
    - linux

virtualenv:
    system_site_packages: false

env:
    global:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1

before_install:
    - pip install -U pip

install:
    - pip install -U tox-travis appveyor-artifacts coveralls codecov

script:
    - tox

after_success:
    - ls
    - coverage report
    - mv .coverage .coverage.travis
    - appveyor-artifacts -m download
    - coverage combine
    - coverage report
    - coveralls
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)
