# appveyor file:
# https://www.appveyor.com/docs/lang/python/

environment:
    matrix:
        - TOXENV: py36
        - TOXENV: py37

build: off

init:
    - set PIPENV_IGNORE_VIRTUALENVS=1

install:
    - pip install tox

test_script:
    - tox
