# appveyor file:
# https://www.appveyor.com/docs/lang/python/

environment:
    matrix:
        - TOXENV: py36
        - TOXENV: py37

build: false

init:
    - set PIPENV_IGNORE_VIRTUALENVS=1

install:
    - pip install -U tox appveyor-artifacts coveralls

test_script:
    - tox

artifacts:
    - path: .coverage
